### ISSUE TITLE
Email addresses in public domain

### ISSUE THREAD

**Issue by routeaccess** [AGV-IIT-KGP/git-sandbox#25]
The current instructions require adding a line to the README containing email addres and name, which leaves the email address in the public domain.

This can be fixed by changing the instructions to enter name alone, or perhaps github username instead of email address.

**Comment by routeaccess** [comment]
Fixed in 095b8a39ab812ffa5b1fe933208dcbddcfff7f17.

Perhaps request garbage-collect to remote email addresses from history ?
@hargup @abinashmeher999

**Comment by hargup** [comment]
> Perhaps we should request a garbage-collect to be run on the repo to remove email addresses from git history ?

Well, git log stores the email address of the authors of the commits, AFAIK you cannot and probably don't need to remove the email addresses from the git history.
